package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache(keyCache = true,column = "app_id")
public class Application extends BaseApplication<Application> {
	public static final int TYPE_WEB_PC=1;//PC网页
	public static final int TYPE_WEB_MOBILE_H5=2;//普通移动H5
	public static final int TYPE_WEB_MP_H5=3;//公众平台H5
	public static final int TYPE_WECHAT_APP=4;//微信小程序
	public static final int TYPE_ALIPAY_APP=5;//支付宝小程序
	public static final int TYPE_DOUYIN_APP=6;//抖音小程序
	public static final int TYPE_BAIDU_APP=7;//百度小程序
	public static final int TYPE_TOUTIAO_APP=8;//头条小程序
	public static final int TYPE_QQ_APP=9;//QQ小程序
	public static final int TYPE_APPLE_IOS_APP=10;//苹果 IOS APP
	public static final int TYPE_ANDROID_APP=11;//安卓 APP
	public static final int TYPE_HYBIRD_APP=12;//HYBIRD-APP
	public static final int TYPE_UNI_APP=13;//UNI-APP
	public static final int TYPE_OTHER_APP=14;//OTHER-APP
	
	public String getTypeName() {
		int type=getType().intValue();
		String name="未设置";
		switch (type) {
		case TYPE_WEB_PC:
			name="PC网页";
			break;
		case TYPE_WEB_MOBILE_H5:
			name="普通移动端H5";
			break;
		case TYPE_WEB_MP_H5:
			name="公众平台H5";
			break;
		case TYPE_WECHAT_APP:
			name="微信小程序";
			break;
		case TYPE_ALIPAY_APP:
			name="支付宝小程序";
			break;
		case TYPE_DOUYIN_APP:
			name="抖音小程序";
			break;
		case TYPE_BAIDU_APP:
			name="百度小程序";
			break;
		case TYPE_QQ_APP:
			name="QQ小程序";
			break;
		case TYPE_APPLE_IOS_APP:
			name="苹果IOS-APP";
			break;
		case TYPE_ANDROID_APP:
			name="安卓-APP";
			break;
		case TYPE_HYBIRD_APP:
			name="混合Hybird-APP";
			break;
		case TYPE_UNI_APP:
			name="UNI-APP";
			break;
		case TYPE_OTHER_APP:
			name="其它";
			break;
		}
		return name;
	}
}
