package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseBom;

/**
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Bom extends BaseBom<Bom> {
	
	public static final Bom dao = new Bom().dao();
	
}
