package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseChangeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChangeLog extends BaseChangeLog<ChangeLog> {
	
}
