package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseDemotable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Demotable extends BaseDemotable<Demotable> {
	public static final Demotable dao = new Demotable().dao();
}
