package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache
public class Dictionary extends BaseDictionary<Dictionary> {
}
