package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseDictionaryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache(keyCache = true,column="type_key")
public class DictionaryType extends BaseDictionaryType<DictionaryType> {
	/**
	 * 层级 一级
	 */
	public static final int MODE_LEVEL_ONE=1;
	/**
	 * 层级 多级
	 */
	public static final int MODE_LEVEL_MUTIL=2;
}
