package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseDownloadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DownloadLog extends BaseDownloadLog<DownloadLog> {
	public static final int DOWNLOADTYPE_MAINUPDATE=1;
	public static final int DOWNLOADTYPE_LIBSUPDATE=2;
}
