package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.base.UnProcessBoolean;
import cn.jbolt.common.model.base.BaseGlobalConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@UnProcessBoolean
@JBoltAutoCache(idCache = false,keyCache = true,column = "config_key")
public class GlobalConfig extends BaseGlobalConfig<GlobalConfig> {
	public static final String TYPE_STRING="string";
	public static final String TYPE_INT="int";
	public static final String TYPE_DECIMAL="decimal";
	public static final String TYPE_BOOLEAN="boolean";
	
	/**
	 * 验证码类型-默认
	 */
	public static final String CAPTCHA_TYPE_DEFAULT="default";

	/**
	 * 验证码类型-GIF动态
	 */
	public static final String CAPTCHA_TYPE_GIF="gif";
	

	/**
	 * 验证码类型-气泡PNG
	 */
	public static final String CAPTCHA_TYPE_BUBBLE_PNG="bubble_png";
}
