package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodsElementContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsElementContent extends BaseGoodsElementContent<GoodsElementContent> {
	
}
