package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodsAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAttr extends BaseGoodsAttr<GoodsAttr> {
	public static final GoodsAttr dao = new GoodsAttr().dao();
}
