package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseGoodsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache
public class GoodsType extends BaseGoodsType<GoodsType> {
	
}
