package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsGroup extends BaseGoodsGroup<GoodsGroup> {
	
}
