package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoods;
import cn.jbolt.common.util.CACHE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	/*************定义Goods中的详情contentType*****************/
	public final static int CONTENT_TYPE_HTML=1;//html格式
	public final static int CONTENT_TYPE_ELEMENT=2;//图片、文字元素格式
	
	/**
	 * 从缓存中快速获取关联的字典数据中的单位名称
	 * @return
	 */
	public String getUnitName(){
		return CACHE.me.getDictionaryName(getGoodsUnit());
	}
	/**
	 * 前端显示处需要的
	 * @return
	 */
	/*public String getRealMainImage(){
		String mainImage=getMainImage();
		if(StrKit.isBlank(mainImage)){
			return "/assets/img/uploadimg.jpg";
		}
		if(StrKit.isBlank(MainConfig.BASEUPLOADPATH_PRE)){
			return mainImage;
		}
		mainImage=mainImage.replace(MainConfig.BASEUPLOADPATH_PRE, "");
		return mainImage;
	}*/
}
