package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseGoodsTypeBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsTypeBrand extends BaseGoodsTypeBrand<GoodsTypeBrand> {
	
}
