package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseGoodsBackCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache
public class GoodsBackCategory extends BaseGoodsBackCategory<GoodsBackCategory> {
	/**
	 * 树形结构上单独使用的
	 * @return
	 */
	public String getEnableName() {
		String name=super.getName();
		Boolean enable=getEnable();
		return (enable!=null&&enable)?name:(name+"[<span class='text-danger'>禁用</span>]");
	}
}
