package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseOrderShipping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderShipping extends BaseOrderShipping<OrderShipping> {
	public static final OrderShipping dao = new OrderShipping().dao();
}
