package cn.jbolt.common.model;

import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache
public class Role extends BaseRole<Role>{
}
