package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSaleManage;

/**
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class SaleManage extends BaseSaleManage<SaleManage> {
	
	public static final SaleManage dao = new SaleManage().dao();
}
