package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShelfCarousel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShelfCarousel extends BaseShelfCarousel<ShelfCarousel> {
	public static final ShelfCarousel dao = new ShelfCarousel().dao();
}
