package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShelfElement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShelfElement extends BaseShelfElement<ShelfElement> {
	public static final ShelfElement dao = new ShelfElement().dao();
}
