package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShelfActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShelfActivity extends BaseShelfActivity<ShelfActivity> {
	public static final ShelfActivity dao = new ShelfActivity().dao();
}
