package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShelfGoodsFloor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShelfGoodsFloor extends BaseShelfGoodsFloor<ShelfGoodsFloor> {
	public static final ShelfGoodsFloor dao = new ShelfGoodsFloor().dao();
}
