package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShelfGoodsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShelfGoodsGroup extends BaseShelfGoodsGroup<ShelfGoodsGroup> {
	public static final ShelfGoodsGroup dao = new ShelfGoodsGroup().dao();
}
