package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseShelf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shelf extends BaseShelf<Shelf> {
	public static final Shelf dao = new Shelf().dao();
}
