package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sku extends BaseSku<Sku> {
	public static final Sku dao = new Sku().dao();
}
