package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSkuItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuItem extends BaseSkuItem<SkuItem> {
	public static final SkuItem dao = new SkuItem().dao();
}
