package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSpecItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecItem extends BaseSpecItem<SpecItem> {
	public static final SpecItem dao = new SpecItem().dao();
}
