package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseSupplymanage;

/**
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Supplymanage extends BaseSupplymanage<Supplymanage> {
	
	public static final Supplymanage dao = new Supplymanage().dao();
	
}
