package cn.jbolt.common.model;

import cn.jbolt._admin.systemlog.SystemLogService;
import cn.jbolt.common.model.base.BaseSystemLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemLog extends BaseSystemLog<SystemLog> {
	/**
	 * 打开方式 URL
	 */
	public static final int OPENTYPE_URL=1;
	/**
	 * 打开方式 DIALOG
	 */
	public static final int OPENTYPE_DIALOG=2;
	/**
	 * 新增
	 */
	public static final int TYPE_SAVE=1;
	/**
	 * 更新
	 */
	public static final int TYPE_UPDATE=2;
	/**
	 * 删除
	 */
	public static final int TYPE_DELETE=3;
	/**
	 * 删除关联子表
	 */
	public static final int TYPE_LINK_DELETE=4;
	/**
	 * 更新关联子表
	 */
	public static final int TYPE_LINK_UPDATE=5;
	/**
	 * 新增关联子表
	 */
	public static final int TYPE_LINK_SAVE=6;
	
	/**
	 * 字典数据分类
	 */
	public static final int TARGETTYPE_DICTIONARY_TYPE=1;
	/**
	 * 字典数据
	 */
	public static final int TARGETTYPE_DICTIONARY=2;
	 
	/**
	 * 权限定义
	 */
	public static final int TARGETTYPE_PERMISSION=3;
	/**
	 * 用户
	 */
	public static final int TARGETTYPE_USER=4;
	/**
	 * 角色
	 */
	public static final int TARGETTYPE_ROLE=5;
	/**
	 * 全局配置
	 */
	public static final int TARGETTYPE_GLOBAL_CONFIG=6;
	/**
	 * JBolt版本
	 */
	public static final int TARGETTYPE_JBOLT_VERSION=7;
	/**
	 * 商品
	 */
	public static final int TARGETTYPE_MALL_GOODS=8;
	/**
	 * 品牌
	 */
	public static final int TARGETTYPE_MALL_BRAND=9;
	/**
	 * 商品后端分类
	 */
	public static final int TARGETTYPE_MALL_GOODS_BACK_CATEGORY=10;
	/**
	 * 商品类型
	 */
	public static final int TARGETTYPE_MALL_GOODS_TYPE=11;
	/**
	 * JBolt第三方libs
	 */
	public static final int TARGETTYPE_JBOLT_UPDATE_LIBS=15;
	/**
	 * JBolt版本指定的更新文件
	 */
	public static final int TARGETTYPE_JBOLT_VERSION_FILE=16;
	/**
	 * JBolt系统的文件库资源库
	 */
	public static final int TARGETTYPE_JBOLT_FILE=17;
	/**
	 * 微信公众平台信息
	 */
	public static final int TARGETTYPE_WECHAT_MPINFO=18;
	/**
	 * 微信公众平台信息-自动回复规则
	 */
	public static final int TARGETTYPE_WECHAT_AUTOREPLY=19;
	/**
	 * 微信公众平台信息-自动回复内容
	 */
	public static final int TARGETTYPE_WECHAT_REPLYCONTENT=20;
	/**
	 * 微信公众平台信息-关键词
	 */
	public static final int TARGETTYPE_WECHAT_KEYWORDS=21;
	
	/**
	 * API应用中心的应用
	 */
	public static final int TARGETTYPE_APPLICATION=22;
	/**
	 * 用户自身配置
	 */
	public static final int TARGETTYPE_USER_CONFIG=23;
	/**
	 * 供应管理
	 */
	public static final int TARGETTYPE_SUPPLYMANAGE_INFO = 24;
	/**
	 * 销售管理
	 */
	public static final int TARGETTYPE_SALEMANAGE_INFO = 25;
	/**
	 * 仓位管理
	 */
	public static final int TARGETTYPE_WAREHOUSEMANAGE_INFO = 26;
	/**
	 * 物料管理
	 */
	public static final int TARGETTYPE_BOM_INFO = 27;
	/**
	 * 客户管理
	 */
	public static final int TARGETTYPE_CUSTOMER_INFO = 28;
	/**
	 * 供应商管理
	 */
	public static final int TARGETTYPE_SUPPLIER_MPINFO = 29;
	/**
	 * 仓库管理
	 */
	public static final int TARGETTYPE_WAREHOUSE_INFO = 30;
	
	public String getTypeName(){
		return SystemLogService.typeName(getType());
	}
	public String getTargetTypeName(){
		return SystemLogService.targetTypeName(getTargetType());
	}
}
