package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseUpdateLibs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UpdateLibs extends BaseUpdateLibs<UpdateLibs> {
	
}
