package cn.jbolt.common.model;


import cn.jbolt.base.JBoltAutoCache;
import cn.jbolt.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@JBoltAutoCache
public class User extends BaseUser<User> {
	public static final int SEX_NONE=0; //未知
	public static final int SEX_MALE=1; //男
	public static final int SEX_FEMALE=2; //女

}
