package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWarehouseManage;

/**
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class WarehouseManage extends BaseWarehouseManage<WarehouseManage> {
	public static final WarehouseManage dao = new WarehouseManage().dao();
}
