package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWarehouse;

/**
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Warehouse extends BaseWarehouse<Warehouse> {
}
