package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatArticle extends BaseWechatArticle<WechatArticle> {
	
}
