package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatMenu extends BaseWechatMenu<WechatMenu> {
	/**
	 * 内置事件
	 */
	public static final String TYPE_EVENT = "click";
	/**
	 * URL地址
	 */
	public static final String TYPE_VIEW= "view";
	/**
	 * 匹配关键词
	 */
	public static final String TYPE_KEYWORDS= "keywords";
	/**
	 * 无跳转
	 */
	public static final String TYPE_NONE= "none";
	/**
	 * 调用系统相机拍照
	 */
	public static final String TYPE_PIC_SYSPHOTO= "pic_sysphoto";
	/**
	 * 调用系统相机拍照或者从相册选择
	 */
	public static final String TYPE_PIC_PHOTO_OR_ALBUM= "pic_photo_or_album";
	/**
	 * 调用微信相册发图
	 */
	public static final String TYPE_PIC_WEIXIN= "pic_weixin";
	/**
	 * 微信小程序
	 */
	public static final String TYPE_MINIPROGRAM= "miniprogram";
}
