package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatReplyContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatReplyContent extends BaseWechatReplyContent<WechatReplyContent> {
	public static final String TYPE_TEXT="text";
	public static final String TYPE_IMG="image";
	public static final String TYPE_VOICE="voice";
	public static final String TYPE_VIDEO="video";
	public static final String TYPE_MUSIC="music";
	public static final String TYPE_NEWS="news";
}
