package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatUser extends BaseWechatUser<WechatUser> {
	public static final WechatUser dao = new WechatUser().dao();
}
