package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatKeywords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatKeywords extends BaseWechatKeywords<WechatKeywords> {
	public static final int TYPE_LIKE=1;//模糊匹配
	public static final int TYPE_EQUALS=2;//全匹配
}
