package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseWechatMedia;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatMedia extends BaseWechatMedia<WechatMedia> {
	public static final String TYPE_IMG="image";
	public static final String TYPE_NEWS="news";
	public static final String TYPE_VIDEO="video";
	public static final String TYPE_VOICE="voice";
	public String getRealImgUrl() {
		return get("realImgUrl");
	}
	public String getRealVoiceUrl() {
		return get("realVoiceUrl");
	}
		
}
