package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDemotable<M extends BaseDemotable<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDemoDate(java.util.Date demoDate) {
		set("demo_date", demoDate);
		return (M)this;
	}
	
	public java.util.Date getDemoDate() {
		return get("demo_date");
	}

	public M setDemoTime(java.sql.Time demoTime) {
		set("demo_time", demoTime);
		return (M)this;
	}
	
	public java.sql.Time getDemoTime() {
		return get("demo_time");
	}

	public M setDemoDateTime(java.util.Date demoDateTime) {
		set("demo_date_time", demoDateTime);
		return (M)this;
	}
	
	public java.util.Date getDemoDateTime() {
		return get("demo_date_time");
	}

	public M setDemoWeek(java.lang.String demoWeek) {
		set("demo_week", demoWeek);
		return (M)this;
	}
	
	public java.lang.String getDemoWeek() {
		return getStr("demo_week");
	}

	public M setDemoMonth(java.lang.String demoMonth) {
		set("demo_month", demoMonth);
		return (M)this;
	}
	
	public java.lang.String getDemoMonth() {
		return getStr("demo_month");
	}

	public M setTime(java.sql.Time time) {
		set("time", time);
		return (M)this;
	}
	
	public java.sql.Time getTime() {
		return get("time");
	}

}
