package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApplication<M extends BaseApplication<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 应用名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 应用名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 应用简介
	 */
	public M setBriefInfo(java.lang.String briefInfo) {
		set("brief_info", briefInfo);
		return (M)this;
	}
	
	/**
	 * 应用简介
	 */
	public java.lang.String getBriefInfo() {
		return getStr("brief_info");
	}

	/**
	 * 应用ID
	 */
	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}
	
	/**
	 * 应用ID
	 */
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	/**
	 * 应用密钥
	 */
	public M setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
		return (M)this;
	}
	
	/**
	 * 应用密钥
	 */
	public java.lang.String getAppSecret() {
		return getStr("app_secret");
	}

	/**
	 * 是否启用
	 */
	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	/**
	 * 是否启用
	 */
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 创建用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 更新用户ID
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新用户ID
	 */
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	/**
	 * app类型
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * app类型
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 是否需要接口校验SIGN
	 */
	public M setNeedCheckSign(java.lang.Boolean needCheckSign) {
		set("need_check_sign", needCheckSign);
		return (M)this;
	}
	
	/**
	 * 是否需要接口校验SIGN
	 */
	public java.lang.Boolean getNeedCheckSign() {
		return getBoolean("need_check_sign");
	}

}
