package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSpecItem<M extends BaseSpecItem<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 选项名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 选项名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 所属规格
	 */
	public M setSpecId(java.lang.Integer specId) {
		set("specId", specId);
		return (M)this;
	}
	
	/**
	 * 所属规格
	 */
	public java.lang.Integer getSpecId() {
		return getInt("specId");
	}

}
