package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatAutoreply<M extends BaseWechatAutoreply<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	/**
	 * 类型 关注回复 无内容时回复 关键词回复
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型 关注回复 无内容时回复 关键词回复
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 规则名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 规则名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 回复类型 全部还是随机一条
	 */
	public M setReplyType(java.lang.Integer replyType) {
		set("reply_type", replyType);
		return (M)this;
	}
	
	/**
	 * 回复类型 全部还是随机一条
	 */
	public java.lang.Integer getReplyType() {
		return getInt("reply_type");
	}

	/**
	 * 记录创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 用户 ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户 ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

}
