package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePermission<M extends BasePermission<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 地址
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 图标
	 */
	public M setIcons(java.lang.String icons) {
		set("icons", icons);
		return (M)this;
	}
	
	/**
	 * 图标
	 */
	public java.lang.String getIcons() {
		return getStr("icons");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 层级
	 */
	public M setPermissionLevel(java.lang.Integer permissionLevel) {
		set("permission_level", permissionLevel);
		return (M)this;
	}
	
	/**
	 * 层级
	 */
	public java.lang.Integer getPermissionLevel() {
		return getInt("permission_level");
	}

	/**
	 * 权限资源KEY
	 */
	public M setPermissionKey(java.lang.String permissionKey) {
		set("permission_key", permissionKey);
		return (M)this;
	}
	
	/**
	 * 权限资源KEY
	 */
	public java.lang.String getPermissionKey() {
		return getStr("permission_key");
	}

	/**
	 * 是否是菜单
	 */
	public M setIsMenu(java.lang.Boolean isMenu) {
		set("is_menu", isMenu);
		return (M)this;
	}
	
	/**
	 * 是否是菜单
	 */
	public java.lang.Boolean getIsMenu() {
		return getBoolean("is_menu");
	}

	/**
	 * 是否新窗口打开
	 */
	public M setIsTargetBlank(java.lang.Boolean isTargetBlank) {
		set("is_target_blank", isTargetBlank);
		return (M)this;
	}
	
	/**
	 * 是否新窗口打开
	 */
	public java.lang.Boolean getIsTargetBlank() {
		return getBoolean("is_target_blank");
	}

	/**
	 * 是否系统超级管理员默认拥有的权限
	 */
	public M setIsSystemAdminDefault(java.lang.Boolean isSystemAdminDefault) {
		set("is_system_admin_default", isSystemAdminDefault);
		return (M)this;
	}
	
	/**
	 * 是否系统超级管理员默认拥有的权限
	 */
	public java.lang.Boolean getIsSystemAdminDefault() {
		return getBoolean("is_system_admin_default");
	}

}
