package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJboltVersionFile<M extends BaseJboltVersionFile<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * jbolt版本ID
	 */
	public M setJboltVersionId(java.lang.Integer jboltVersionId) {
		set("jbolt_version_id", jboltVersionId);
		return (M)this;
	}
	
	/**
	 * jbolt版本ID
	 */
	public java.lang.Integer getJboltVersionId() {
		return getInt("jbolt_version_id");
	}

}
