package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGlobalConfig<M extends BaseGlobalConfig<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 配置KEY
	 */
	public M setConfigKey(java.lang.String configKey) {
		set("config_key", configKey);
		return (M)this;
	}
	
	/**
	 * 配置KEY
	 */
	public java.lang.String getConfigKey() {
		return getStr("config_key");
	}

	/**
	 * 配置项值
	 */
	public M setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
		return (M)this;
	}
	
	/**
	 * 配置项值
	 */
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 创建用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 创建用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 更新用户ID
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新用户ID
	 */
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 值类型
	 */
	public M setValueType(java.lang.String valueType) {
		set("value_type", valueType);
		return (M)this;
	}
	
	/**
	 * 值类型
	 */
	public java.lang.String getValueType() {
		return getStr("value_type");
	}

}
