package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupplymanage<M extends BaseSupplymanage<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 供应商编号
	 */
	public M setSupplierId(java.lang.Integer supplierId) {
		set("supplierId", supplierId);
		return (M)this;
	}
	
	/**
	 * 供应商编号
	 */
	public java.lang.Integer getSupplierId() {
		return getInt("supplierId");
	}

	/**
	 * 供应商名称
	 */
	public M setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
		return (M)this;
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}

	/**
	 * 收货日期
	 */
	public M setReceiptDate(java.util.Date receiptDate) {
		set("receiptDate", receiptDate);
		return (M)this;
	}
	
	/**
	 * 收货日期
	 */
	public java.util.Date getReceiptDate() {
		return get("receiptDate");
	}

	/**
	 * 型号
	 */
	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getModel() {
		return getStr("model");
	}

	/**
	 * 箱数
	 */
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 箱数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 每箱数量
	 */
	public M setNumPerBox(java.lang.Integer numPerBox) {
		set("numPerBox", numPerBox);
		return (M)this;
	}
	
	/**
	 * 每箱数量
	 */
	public java.lang.Integer getNumPerBox() {
		return getInt("numPerBox");
	}

	/**
	 * 总数量
	 */
	public M setTotalNum(java.lang.Integer totalNum) {
		set("totalNum", totalNum);
		return (M)this;
	}
	
	/**
	 * 总数量
	 */
	public java.lang.Integer getTotalNum() {
		return getInt("totalNum");
	}

	/**
	 * 单价
	 */
	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 总金额
	 */
	public M setTotalMoney(java.math.BigDecimal totalMoney) {
		set("totalMoney", totalMoney);
		return (M)this;
	}
	
	/**
	 * 总金额
	 */
	public java.math.BigDecimal getTotalMoney() {
		return get("totalMoney");
	}

	/**
	 * 付款金额
	 */
	public M setPayMoney(java.math.BigDecimal payMoney) {
		set("payMoney", payMoney);
		return (M)this;
	}
	
	/**
	 * 付款金额
	 */
	public java.math.BigDecimal getPayMoney() {
		return get("payMoney");
	}

	/**
	 * 付款日期
	 */
	public M setPayDate(java.util.Date payDate) {
		set("payDate", payDate);
		return (M)this;
	}
	
	/**
	 * 付款日期
	 */
	public java.util.Date getPayDate() {
		return get("payDate");
	}

	/**
	 * 待付款
	 */
	public M setWaitPay(java.math.BigDecimal waitPay) {
		set("waitPay", waitPay);
		return (M)this;
	}
	
	/**
	 * 待付款
	 */
	public java.math.BigDecimal getWaitPay() {
		return get("waitPay");
	}

	/**
	 * 待收款
	 */
	public M setWaitReceipt(java.math.BigDecimal waitReceipt) {
		set("waitReceipt", waitReceipt);
		return (M)this;
	}
	
	/**
	 * 待收款
	 */
	public java.math.BigDecimal getWaitReceipt() {
		return get("waitReceipt");
	}

	/**
	 * 日期
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 日期
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
