package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderItem<M extends BaseOrderItem<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单ID
	 */
	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	/**
	 * 订单ID
	 */
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	/**
	 * 商品ID
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品ID
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品名称
	 */
	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 二级促销标题
	 */
	public M setGoodsSubTitle(java.lang.String goodsSubTitle) {
		set("goods_sub_title", goodsSubTitle);
		return (M)this;
	}
	
	/**
	 * 二级促销标题
	 */
	public java.lang.String getGoodsSubTitle() {
		return getStr("goods_sub_title");
	}

	/**
	 * 单价
	 */
	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 商品数量
	 */
	public M setGoodsCount(java.lang.Integer goodsCount) {
		set("goods_count", goodsCount);
		return (M)this;
	}
	
	/**
	 * 商品数量
	 */
	public java.lang.Integer getGoodsCount() {
		return getInt("goods_count");
	}

	/**
	 * 总额
	 */
	public M setGoodsAmount(java.math.BigDecimal goodsAmount) {
		set("goods_amount", goodsAmount);
		return (M)this;
	}
	
	/**
	 * 总额
	 */
	public java.math.BigDecimal getGoodsAmount() {
		return get("goods_amount");
	}

	/**
	 * 商品图
	 */
	public M setGoodsImage(java.lang.String goodsImage) {
		set("goods_image", goodsImage);
		return (M)this;
	}
	
	/**
	 * 商品图
	 */
	public java.lang.String getGoodsImage() {
		return getStr("goods_image");
	}

	/**
	 * 订单编号
	 */
	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	/**
	 * 订单编号
	 */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 原价
	 */
	public M setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
		return (M)this;
	}
	
	/**
	 * 原价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 单个节省价格
	 */
	public M setSavePrice(java.math.BigDecimal savePrice) {
		set("save_price", savePrice);
		return (M)this;
	}
	
	/**
	 * 单个节省价格
	 */
	public java.math.BigDecimal getSavePrice() {
		return get("save_price");
	}

	/**
	 * 一共节省多少钱
	 */
	public M setSaveAmount(java.math.BigDecimal saveAmount) {
		set("save_amount", saveAmount);
		return (M)this;
	}
	
	/**
	 * 一共节省多少钱
	 */
	public java.math.BigDecimal getSaveAmount() {
		return get("save_amount");
	}

}
