package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 订单编号
	 */
	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	/**
	 * 订单编号
	 */
	public java.lang.String getOrderNo() {
		return getStr("order_no");
	}

	/**
	 * 下单时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 下单时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 买家ID
	 */
	public M setBuyerId(java.lang.Integer buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}
	
	/**
	 * 买家ID
	 */
	public java.lang.Integer getBuyerId() {
		return getInt("buyer_id");
	}

	/**
	 * 冗余买家名字
	 */
	public M setBuyerName(java.lang.String buyerName) {
		set("buyer_name", buyerName);
		return (M)this;
	}
	
	/**
	 * 冗余买家名字
	 */
	public java.lang.String getBuyerName() {
		return getStr("buyer_name");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 付款时间
	 */
	public M setPaymentTime(java.util.Date paymentTime) {
		set("payment_time", paymentTime);
		return (M)this;
	}
	
	/**
	 * 付款时间
	 */
	public java.util.Date getPaymentTime() {
		return get("payment_time");
	}

	/**
	 * 发货时间
	 */
	public M setConsignTime(java.util.Date consignTime) {
		set("consign_time", consignTime);
		return (M)this;
	}
	
	/**
	 * 发货时间
	 */
	public java.util.Date getConsignTime() {
		return get("consign_time");
	}

	/**
	 * 交易完成时间
	 */
	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}
	
	/**
	 * 交易完成时间
	 */
	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	/**
	 * 订单关闭时间
	 */
	public M setCloseTime(java.util.Date closeTime) {
		set("close_time", closeTime);
		return (M)this;
	}
	
	/**
	 * 订单关闭时间
	 */
	public java.util.Date getCloseTime() {
		return get("close_time");
	}

	/**
	 * 卖家留言
	 */
	public M setBuyerMessage(java.lang.String buyerMessage) {
		set("buyer_message", buyerMessage);
		return (M)this;
	}
	
	/**
	 * 卖家留言
	 */
	public java.lang.String getBuyerMessage() {
		return getStr("buyer_message");
	}

	/**
	 * 买家是否已经评价
	 */
	public M setBuyerRate(java.lang.Boolean buyerRate) {
		set("buyer_rate", buyerRate);
		return (M)this;
	}
	
	/**
	 * 买家是否已经评价
	 */
	public java.lang.Boolean getBuyerRate() {
		return getBoolean("buyer_rate");
	}

	/**
	 * 订单状态 待付款 已付款 已发货 订单完成 订单关闭
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 订单状态 待付款 已付款 已发货 订单完成 订单关闭
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 总额
	 */
	public M setGoodsAmount(java.math.BigDecimal goodsAmount) {
		set("goods_amount", goodsAmount);
		return (M)this;
	}
	
	/**
	 * 总额
	 */
	public java.math.BigDecimal getGoodsAmount() {
		return get("goods_amount");
	}

	/**
	 * 运费
	 */
	public M setPostFee(java.math.BigDecimal postFee) {
		set("post_fee", postFee);
		return (M)this;
	}
	
	/**
	 * 运费
	 */
	public java.math.BigDecimal getPostFee() {
		return get("post_fee");
	}

	/**
	 * 应付总额
	 */
	public M setPaymentAmount(java.math.BigDecimal paymentAmount) {
		set("payment_amount", paymentAmount);
		return (M)this;
	}
	
	/**
	 * 应付总额
	 */
	public java.math.BigDecimal getPaymentAmount() {
		return get("payment_amount");
	}

	/**
	 * 支付类型 在线支付 货到付款
	 */
	public M setPaymentType(java.lang.Integer paymentType) {
		set("payment_type", paymentType);
		return (M)this;
	}
	
	/**
	 * 支付类型 在线支付 货到付款
	 */
	public java.lang.Integer getPaymentType() {
		return getInt("payment_type");
	}

	/**
	 * 在线支付选择了谁
	 */
	public M setOnlinePaymentType(java.lang.Integer onlinePaymentType) {
		set("online_payment_type", onlinePaymentType);
		return (M)this;
	}
	
	/**
	 * 在线支付选择了谁
	 */
	public java.lang.Integer getOnlinePaymentType() {
		return getInt("online_payment_type");
	}

	/**
	 * 通过什么方式关闭 后台管理 or 客户自身
	 */
	public M setCloseType(java.lang.Integer closeType) {
		set("close_type", closeType);
		return (M)this;
	}
	
	/**
	 * 通过什么方式关闭 后台管理 or 客户自身
	 */
	public java.lang.Integer getCloseType() {
		return getInt("close_type");
	}

	/**
	 * 关闭订单用户ID
	 */
	public M setCloseUesrId(java.lang.Integer closeUesrId) {
		set("close_uesr_id", closeUesrId);
		return (M)this;
	}
	
	/**
	 * 关闭订单用户ID
	 */
	public java.lang.Integer getCloseUesrId() {
		return getInt("close_uesr_id");
	}

}
