package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSaleManage<M extends BaseSaleManage<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 供应商编号
	 */
	public M setSupplierId(java.lang.Integer supplierId) {
		set("supplierId", supplierId);
		return (M)this;
	}
	
	/**
	 * 供应商编号
	 */
	public java.lang.Integer getSupplierId() {
		return getInt("supplierId");
	}

	/**
	 * 供应商名称
	 */
	public M setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
		return (M)this;
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}

	/**
	 * 发货日期
	 */
	public M setShipDate(java.util.Date shipDate) {
		set("shipDate", shipDate);
		return (M)this;
	}
	
	/**
	 * 发货日期
	 */
	public java.util.Date getShipDate() {
		return get("shipDate");
	}

	/**
	 * 型号
	 */
	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getModel() {
		return getStr("model");
	}

	/**
	 * 箱数
	 */
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 箱数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 每箱数
	 */
	public M setNumPerBox(java.lang.Integer numPerBox) {
		set("numPerBox", numPerBox);
		return (M)this;
	}
	
	/**
	 * 每箱数
	 */
	public java.lang.Integer getNumPerBox() {
		return getInt("numPerBox");
	}

	/**
	 * 总数量
	 */
	public M setTotalNum(java.lang.Integer totalNum) {
		set("totalNum", totalNum);
		return (M)this;
	}
	
	/**
	 * 总数量
	 */
	public java.lang.Integer getTotalNum() {
		return getInt("totalNum");
	}

	/**
	 * 单价
	 */
	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 总金额
	 */
	public M setTotalMoney(java.math.BigDecimal totalMoney) {
		set("totalMoney", totalMoney);
		return (M)this;
	}
	
	/**
	 * 总金额
	 */
	public java.math.BigDecimal getTotalMoney() {
		return get("totalMoney");
	}

	/**
	 * 已收金额
	 */
	public M setReceiptMoney(java.math.BigDecimal receiptMoney) {
		set("receiptMoney", receiptMoney);
		return (M)this;
	}
	
	/**
	 * 已收金额
	 */
	public java.math.BigDecimal getReceiptMoney() {
		return get("receiptMoney");
	}

	/**
	 * 收款日期
	 */
	public M setReceiptDate(java.util.Date receiptDate) {
		set("receiptDate", receiptDate);
		return (M)this;
	}
	
	/**
	 * 收款日期
	 */
	public java.util.Date getReceiptDate() {
		return get("receiptDate");
	}

	/**
	 * 待付金额
	 */
	public M setWaitPay(java.math.BigDecimal waitPay) {
		set("waitPay", waitPay);
		return (M)this;
	}
	
	/**
	 * 待付金额
	 */
	public java.math.BigDecimal getWaitPay() {
		return get("waitPay");
	}

	/**
	 * 待收金额
	 */
	public M setWaitReceipt(java.math.BigDecimal waitReceipt) {
		set("waitReceipt", waitReceipt);
		return (M)this;
	}
	
	/**
	 * 待收金额
	 */
	public java.math.BigDecimal getWaitReceipt() {
		return get("waitReceipt");
	}

	/**
	 * 日期
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 日期
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 已收金额2
	 */
	public M setReceiptMoney2(java.math.BigDecimal receiptMoney2) {
		set("receiptMoney2", receiptMoney2);
		return (M)this;
	}
	
	/**
	 * 已收金额2
	 */
	public java.math.BigDecimal getReceiptMoney2() {
		return get("receiptMoney2");
	}

	/**
	 * 收款日期2
	 */
	public M setReceiptDate2(java.util.Date receiptDate2) {
		set("receiptDate2", receiptDate2);
		return (M)this;
	}
	
	/**
	 * 收款日期2
	 */
	public java.util.Date getReceiptDate2() {
		return get("receiptDate2");
	}

	/**
	 * 已收金额3
	 */
	public M setReceiptMoney3(java.math.BigDecimal receiptMoney3) {
		set("receiptMoney3", receiptMoney3);
		return (M)this;
	}
	
	/**
	 * 已收金额3
	 */
	public java.math.BigDecimal getReceiptMoney3() {
		return get("receiptMoney3");
	}

	/**
	 * 收款日期3
	 */
	public M setReceiptDate3(java.util.Date receiptDate3) {
		set("receiptDate3", receiptDate3);
		return (M)this;
	}
	
	/**
	 * 收款日期3
	 */
	public java.util.Date getReceiptDate3() {
		return get("receiptDate3");
	}

	/**
	 * 已收金额4
	 */
	public M setReceiptMoney4(java.math.BigDecimal receiptMoney4) {
		set("receiptMoney4", receiptMoney4);
		return (M)this;
	}
	
	/**
	 * 已收金额4
	 */
	public java.math.BigDecimal getReceiptMoney4() {
		return get("receiptMoney4");
	}

	/**
	 * 收款日期4
	 */
	public M setReceiptDate4(java.util.Date receiptDate4) {
		set("receiptDate4", receiptDate4);
		return (M)this;
	}
	
	/**
	 * 收款日期4
	 */
	public java.util.Date getReceiptDate4() {
		return get("receiptDate4");
	}

	/**
	 * 已收金额5
	 */
	public M setReceiptMoney5(java.math.BigDecimal receiptMoney5) {
		set("receiptMoney5", receiptMoney5);
		return (M)this;
	}
	
	/**
	 * 已收金额5
	 */
	public java.math.BigDecimal getReceiptMoney5() {
		return get("receiptMoney5");
	}

	/**
	 * 收款日期5
	 */
	public M setReceiptDate5(java.util.Date receiptDate5) {
		set("receiptDate5", receiptDate5);
		return (M)this;
	}
	
	/**
	 * 收款日期5
	 */
	public java.util.Date getReceiptDate5() {
		return get("receiptDate5");
	}

}
