package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShelfElement<M extends BaseShelfElement<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型 轮播 楼层 分类 活动等
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型 轮播 楼层 分类 活动等
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 宽度
	 */
	public M setWidth(java.lang.String width) {
		set("width", width);
		return (M)this;
	}
	
	/**
	 * 宽度
	 */
	public java.lang.String getWidth() {
		return getStr("width");
	}

	/**
	 * 高度
	 */
	public M setHeight(java.lang.String height) {
		set("height", height);
		return (M)this;
	}
	
	/**
	 * 高度
	 */
	public java.lang.String getHeight() {
		return getStr("height");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

}
