package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 客户编号
	 */
	public M setCustomerNo(java.lang.String customerNo) {
		set("customerNo", customerNo);
		return (M)this;
	}
	
	/**
	 * 客户编号
	 */
	public java.lang.String getCustomerNo() {
		return getStr("customerNo");
	}

	/**
	 * 客户姓名
	 */
	public M setCustomerName(java.lang.String customerName) {
		set("customerName", customerName);
		return (M)this;
	}
	
	/**
	 * 客户姓名
	 */
	public java.lang.String getCustomerName() {
		return getStr("customerName");
	}

	/**
	 * 客户地区
	 */
	public M setCustomerArea(java.lang.Integer customerArea) {
		set("customerArea", customerArea);
		return (M)this;
	}
	
	/**
	 * 客户地区
	 */
	public java.lang.Integer getCustomerArea() {
		return getInt("customerArea");
	}

	/**
	 * 客户级别
	 */
	public M setCustomerLevel(java.lang.Integer customerLevel) {
		set("customerLevel", customerLevel);
		return (M)this;
	}
	
	/**
	 * 客户级别
	 */
	public java.lang.Integer getCustomerLevel() {
		return getInt("customerLevel");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
