package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBrand<M extends BaseBrand<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 网址
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 网址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * logo地址
	 */
	public M setLogo(java.lang.String logo) {
		set("logo", logo);
		return (M)this;
	}
	
	/**
	 * logo地址
	 */
	public java.lang.String getLogo() {
		return getStr("logo");
	}

	/**
	 * 备注描述
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注描述
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 英文名
	 */
	public M setEnglishName(java.lang.String englishName) {
		set("english_name", englishName);
		return (M)this;
	}
	
	/**
	 * 英文名
	 */
	public java.lang.String getEnglishName() {
		return getStr("english_name");
	}

}
