package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShelf<M extends BaseShelf<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 创建人ID
	 */
	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建人ID
	 */
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	/**
	 * 上线发布人
	 */
	public M setPublishUserId(java.lang.Integer publishUserId) {
		set("publish_user_id", publishUserId);
		return (M)this;
	}
	
	/**
	 * 上线发布人
	 */
	public java.lang.Integer getPublishUserId() {
		return getInt("publish_user_id");
	}

	/**
	 * 发布时间
	 */
	public M setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
		return (M)this;
	}
	
	/**
	 * 发布时间
	 */
	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	/**
	 * 分享图
	 */
	public M setShareImage(java.lang.String shareImage) {
		set("share_image", shareImage);
		return (M)this;
	}
	
	/**
	 * 分享图
	 */
	public java.lang.String getShareImage() {
		return getStr("share_image");
	}

	/**
	 * 分享标题
	 */
	public M setShareTitle(java.lang.String shareTitle) {
		set("share_title", shareTitle);
		return (M)this;
	}
	
	/**
	 * 分享标题
	 */
	public java.lang.String getShareTitle() {
		return getStr("share_title");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 更新人
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新人
	 */
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

}
