package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJboltVersion<M extends BaseJboltVersion<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	/**
	 * 发布时间
	 */
	public M setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
		return (M)this;
	}
	
	/**
	 * 发布时间
	 */
	public java.util.Date getPublishTime() {
		return get("publish_time");
	}

	/**
	 * 是否最新版
	 */
	public M setIsNew(java.lang.Boolean isNew) {
		set("is_new", isNew);
		return (M)this;
	}
	
	/**
	 * 是否最新版
	 */
	public java.lang.Boolean getIsNew() {
		return getBoolean("is_new");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

}
