package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSku<M extends BaseSku<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 规格编码
	 */
	public M setSkuKey(java.lang.String skuKey) {
		set("sku_key", skuKey);
		return (M)this;
	}
	
	/**
	 * 规格编码
	 */
	public java.lang.String getSkuKey() {
		return getStr("sku_key");
	}

	/**
	 * 规格名称
	 */
	public M setSkuName(java.lang.String skuName) {
		set("sku_name", skuName);
		return (M)this;
	}
	
	/**
	 * 规格名称
	 */
	public java.lang.String getSkuName() {
		return getStr("sku_name");
	}

	/**
	 * 商品ID
	 */
	public M setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
		return (M)this;
	}
	
	/**
	 * 商品ID
	 */
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	/**
	 * 商品名称
	 */
	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}
	
	/**
	 * 商品名称
	 */
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	/**
	 * 类型ID
	 */
	public M setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
		return (M)this;
	}
	
	/**
	 * 类型ID
	 */
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	/**
	 * 单价
	 */
	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	/**
	 * 原价
	 */
	public M setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
		return (M)this;
	}
	
	/**
	 * 原价
	 */
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	/**
	 * 库存量
	 */
	public M setStockCount(java.lang.String stockCount) {
		set("stock_count", stockCount);
		return (M)this;
	}
	
	/**
	 * 库存量
	 */
	public java.lang.String getStockCount() {
		return getStr("stock_count");
	}

	/**
	 * 营销语
	 */
	public M setSubTitle(java.lang.String subTitle) {
		set("sub_title", subTitle);
		return (M)this;
	}
	
	/**
	 * 营销语
	 */
	public java.lang.String getSubTitle() {
		return getStr("sub_title");
	}

	/**
	 * 是否上架
	 */
	public M setOnSale(java.lang.Boolean onSale) {
		set("on_sale", onSale);
		return (M)this;
	}
	
	/**
	 * 是否上架
	 */
	public java.lang.Boolean getOnSale() {
		return getBoolean("on_sale");
	}

	/**
	 * 售罄
	 */
	public M setSellout(java.lang.Boolean sellout) {
		set("sellout", sellout);
		return (M)this;
	}
	
	/**
	 * 售罄
	 */
	public java.lang.Boolean getSellout() {
		return getBoolean("sellout");
	}

	/**
	 * 真实销量
	 */
	public M setRealSaleCount(java.lang.Integer realSaleCount) {
		set("real_sale_count", realSaleCount);
		return (M)this;
	}
	
	/**
	 * 真实销量
	 */
	public java.lang.Integer getRealSaleCount() {
		return getInt("real_sale_count");
	}

	/**
	 * 展示营销销量
	 */
	public M setShowSaleCount(java.lang.Integer showSaleCount) {
		set("show_sale_count", showSaleCount);
		return (M)this;
	}
	
	/**
	 * 展示营销销量
	 */
	public java.lang.Integer getShowSaleCount() {
		return getInt("show_sale_count");
	}

	/**
	 * 主图
	 */
	public M setMainImage(java.lang.String mainImage) {
		set("main_image", mainImage);
		return (M)this;
	}
	
	/**
	 * 主图
	 */
	public java.lang.String getMainImage() {
		return getStr("main_image");
	}

	/**
	 * 附图
	 */
	public M setExtraImages(java.lang.String extraImages) {
		set("extraImages", extraImages);
		return (M)this;
	}
	
	/**
	 * 附图
	 */
	public java.lang.String getExtraImages() {
		return getStr("extraImages");
	}

	/**
	 * 热销
	 */
	public M setIsHot(java.lang.Boolean isHot) {
		set("is_hot", isHot);
		return (M)this;
	}
	
	/**
	 * 热销
	 */
	public java.lang.Boolean getIsHot() {
		return getBoolean("is_hot");
	}

	/**
	 * 推荐
	 */
	public M setIsRecommend(java.lang.Boolean isRecommend) {
		set("is_recommend", isRecommend);
		return (M)this;
	}
	
	/**
	 * 推荐
	 */
	public java.lang.Boolean getIsRecommend() {
		return getBoolean("is_recommend");
	}

	/**
	 * 是否需要详情描述
	 */
	public M setNeedContent(java.lang.Boolean needContent) {
		set("need_content", needContent);
		return (M)this;
	}
	
	/**
	 * 是否需要详情描述
	 */
	public java.lang.Boolean getNeedContent() {
		return getBoolean("need_content");
	}

	/**
	 * 描述类型 是富文本还是分开的图片 文本段数据
	 */
	public M setContentType(java.lang.Integer contentType) {
		set("content_type", contentType);
		return (M)this;
	}
	
	/**
	 * 描述类型 是富文本还是分开的图片 文本段数据
	 */
	public java.lang.Integer getContentType() {
		return getInt("content_type");
	}

	/**
	 * 下架时间
	 */
	public M setUnderTime(java.util.Date underTime) {
		set("under_time", underTime);
		return (M)this;
	}
	
	/**
	 * 下架时间
	 */
	public java.util.Date getUnderTime() {
		return get("under_time");
	}

	/**
	 * 上架时间
	 */
	public M setOnsaleTime(java.util.Date onsaleTime) {
		set("onSale_time", onsaleTime);
		return (M)this;
	}
	
	/**
	 * 上架时间
	 */
	public java.util.Date getOnsaleTime() {
		return get("onSale_time");
	}

	/**
	 * 创建人
	 */
	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建人
	 */
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 最后更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 最后更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 最后更新人
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 最后更新人
	 */
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

}
