package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWarehouseManage<M extends BaseWarehouseManage<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 物料编号
	 */
	public M setBomId(java.lang.Integer bomId) {
		set("bomId", bomId);
		return (M)this;
	}
	
	/**
	 * 物料编号
	 */
	public java.lang.Integer getBomId() {
		return getInt("bomId");
	}

	/**
	 * 物料名称
	 */
	public M setMaterialName(java.lang.String materialName) {
		set("materialName", materialName);
		return (M)this;
	}
	
	/**
	 * 物料名称
	 */
	public java.lang.String getMaterialName() {
		return getStr("materialName");
	}

	/**
	 * 物料类型
	 */
	public M setMaterialType(java.lang.Integer materialType) {
		set("materialType", materialType);
		return (M)this;
	}
	
	/**
	 * 物料类型
	 */
	public java.lang.Integer getMaterialType() {
		return getInt("materialType");
	}

	/**
	 * 物料型号
	 */
	public M setMaterialModel(java.lang.Integer materialModel) {
		set("materialModel", materialModel);
		return (M)this;
	}
	
	/**
	 * 物料型号
	 */
	public java.lang.Integer getMaterialModel() {
		return getInt("materialModel");
	}

	/**
	 * 生成工序
	 */
	public M setProductionProcesses(java.lang.Integer productionProcesses) {
		set("productionProcesses", productionProcesses);
		return (M)this;
	}
	
	/**
	 * 生成工序
	 */
	public java.lang.Integer getProductionProcesses() {
		return getInt("productionProcesses");
	}

	/**
	 * 数量
	 */
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 数量
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 入库日期
	 */
	public M setInDate(java.util.Date inDate) {
		set("inDate", inDate);
		return (M)this;
	}
	
	/**
	 * 入库日期
	 */
	public java.util.Date getInDate() {
		return get("inDate");
	}

	/**
	 * 出库日期
	 */
	public M setOutDate(java.util.Date outDate) {
		set("outDate", outDate);
		return (M)this;
	}
	
	/**
	 * 出库日期
	 */
	public java.util.Date getOutDate() {
		return get("outDate");
	}

	/**
	 * 库位余位
	 */
	public M setLocationNum(java.lang.Integer locationNum) {
		set("locationNum", locationNum);
		return (M)this;
	}
	
	/**
	 * 库位余位
	 */
	public java.lang.Integer getLocationNum() {
		return getInt("locationNum");
	}

	/**
	 * 日期
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 日期
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
