package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWarehouse<M extends BaseWarehouse<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 仓库名称
	 */
	public M setWarehouseName(java.lang.String warehouseName) {
		set("warehouseName", warehouseName);
		return (M)this;
	}
	
	/**
	 * 仓库名称
	 */
	public java.lang.String getWarehouseName() {
		return getStr("warehouseName");
	}

	/**
	 * 仓库位置
	 */
	public M setWarehousePosition(java.lang.Integer warehousePosition) {
		set("warehousePosition", warehousePosition);
		return (M)this;
	}
	
	/**
	 * 仓库位置
	 */
	public java.lang.Integer getWarehousePosition() {
		return getInt("warehousePosition");
	}

	/**
	 * 仓库类型
	 */
	public M setWarehouseType(java.lang.Integer warehouseType) {
		set("warehouseType", warehouseType);
		return (M)this;
	}
	
	/**
	 * 仓库类型
	 */
	public java.lang.Integer getWarehouseType() {
		return getInt("warehouseType");
	}

	/**
	 * 库位数量
	 */
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 库位数量
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 添加时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 添加时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
