package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBom<M extends BaseBom<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 物料名称
	 */
	public M setMaterialName(java.lang.String materialName) {
		set("materialName", materialName);
		return (M)this;
	}
	
	/**
	 * 物料名称
	 */
	public java.lang.String getMaterialName() {
		return getStr("materialName");
	}

	/**
	 * 物料种类
	 */
	public M setMaterialType(java.lang.Integer materialType) {
		set("materialType", materialType);
		return (M)this;
	}
	
	/**
	 * 物料种类
	 */
	public java.lang.Integer getMaterialType() {
		return getInt("materialType");
	}

	/**
	 * 物料型号
	 */
	public M setMaterialModel(java.lang.Integer materialModel) {
		set("materialModel", materialModel);
		return (M)this;
	}
	
	/**
	 * 物料型号
	 */
	public java.lang.Integer getMaterialModel() {
		return getInt("materialModel");
	}

	public M setProductionProcesses(java.lang.Integer productionProcesses) {
		set("productionProcesses", productionProcesses);
		return (M)this;
	}
	
	public java.lang.Integer getProductionProcesses() {
		return getInt("productionProcesses");
	}

}
