package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsTypeBrand<M extends BaseGoodsTypeBrand<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 关联商品类型
	 */
	public M setGoodsTypeId(java.lang.Integer goodsTypeId) {
		set("goods_type_id", goodsTypeId);
		return (M)this;
	}
	
	/**
	 * 关联商品类型
	 */
	public java.lang.Integer getGoodsTypeId() {
		return getInt("goods_type_id");
	}

	/**
	 * 关联商品品牌
	 */
	public M setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
		return (M)this;
	}
	
	/**
	 * 关联商品品牌
	 */
	public java.lang.Integer getBrandId() {
		return getInt("brand_id");
	}

}
