package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsType<M extends BaseGoodsType<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 是否启用
	 */
	public M setEnable(java.lang.Boolean enable) {
		set("enable", enable);
		return (M)this;
	}
	
	/**
	 * 是否启用
	 */
	public java.lang.Boolean getEnable() {
		return getBoolean("enable");
	}

	/**
	 * 排序
	 */
	public M setSortRank(java.lang.Integer sortRank) {
		set("sort_rank", sortRank);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getSortRank() {
		return getInt("sort_rank");
	}

	/**
	 * 规格数量
	 */
	public M setSpecCount(java.lang.Integer specCount) {
		set("spec_count", specCount);
		return (M)this;
	}
	
	/**
	 * 规格数量
	 */
	public java.lang.Integer getSpecCount() {
		return getInt("spec_count");
	}

	/**
	 * 属性数量
	 */
	public M setAttrCount(java.lang.Integer attrCount) {
		set("attr_count", attrCount);
		return (M)this;
	}
	
	/**
	 * 属性数量
	 */
	public java.lang.Integer getAttrCount() {
		return getInt("attr_count");
	}

	/**
	 * 品牌数量
	 */
	public M setBrandCount(java.lang.Integer brandCount) {
		set("brand_count", brandCount);
		return (M)this;
	}
	
	/**
	 * 品牌数量
	 */
	public java.lang.Integer getBrandCount() {
		return getInt("brand_count");
	}

	/**
	 * 拼音
	 */
	public M setPinyin(java.lang.String pinyin) {
		set("pinyin", pinyin);
		return (M)this;
	}
	
	/**
	 * 拼音
	 */
	public java.lang.String getPinyin() {
		return getStr("pinyin");
	}

	/**
	 * 备注信息
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
