package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatKeywords<M extends BaseWechatKeywords<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 模糊 全匹配
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 模糊 全匹配
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 回复规则ID
	 */
	public M setAutoReplyId(java.lang.Integer autoReplyId) {
		set("auto_reply_id", autoReplyId);
		return (M)this;
	}
	
	/**
	 * 回复规则ID
	 */
	public java.lang.Integer getAutoReplyId() {
		return getInt("auto_reply_id");
	}

}
