package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatArticle<M extends BaseWechatArticle<M>> extends JBoltBaseModel<M>{

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 用户 ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户 ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 更新用户 ID
	 */
	public M setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
		return (M)this;
	}
	
	/**
	 * 更新用户 ID
	 */
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	/**
	 * 文章摘要
	 */
	public M setBriefInfo(java.lang.String briefInfo) {
		set("brief_info", briefInfo);
		return (M)this;
	}
	
	/**
	 * 文章摘要
	 */
	public java.lang.String getBriefInfo() {
		return getStr("brief_info");
	}

	public M setPoster(java.lang.String poster) {
		set("poster", poster);
		return (M)this;
	}
	
	public java.lang.String getPoster() {
		return getStr("poster");
	}

	/**
	 * 阅读数
	 */
	public M setViewCount(java.lang.Integer viewCount) {
		set("view_count", viewCount);
		return (M)this;
	}
	
	/**
	 * 阅读数
	 */
	public java.lang.Integer getViewCount() {
		return getInt("view_count");
	}

	/**
	 * 微信素材 ID
	 */
	public M setMediaId(java.lang.String mediaId) {
		set("media_id", mediaId);
		return (M)this;
	}
	
	/**
	 * 微信素材 ID
	 */
	public java.lang.String getMediaId() {
		return getStr("media_id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	/**
	 * 图文链接地址
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 图文链接地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 本地图文 公众号图文素材 外部图文
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 本地图文 公众号图文素材 外部图文
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
