package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDownloadLog<M extends BaseDownloadLog<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIpaddress(java.lang.String ipaddress) {
		set("ipaddress", ipaddress);
		return (M)this;
	}
	
	public java.lang.String getIpaddress() {
		return getStr("ipaddress");
	}

	/**
	 * 下载类型
	 */
	public M setDownloadType(java.lang.Integer downloadType) {
		set("download_type", downloadType);
		return (M)this;
	}
	
	/**
	 * 下载类型
	 */
	public java.lang.Integer getDownloadType() {
		return getInt("download_type");
	}

	/**
	 * 下载时间
	 */
	public M setDownloadTime(java.util.Date downloadTime) {
		set("download_time", downloadTime);
		return (M)this;
	}
	
	/**
	 * 下载时间
	 */
	public java.util.Date getDownloadTime() {
		return get("download_time");
	}

}
