package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudent<M extends BaseStudent<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setGender(java.lang.String gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.String getGender() {
		return getStr("gender");
	}

	public M setSno(java.lang.Integer sno) {
		set("sno", sno);
		return (M)this;
	}
	
	public java.lang.Integer getSno() {
		return getInt("sno");
	}

	public M setClazz(java.lang.String clazz) {
		set("clazz", clazz);
		return (M)this;
	}
	
	public java.lang.String getClazz() {
		return getStr("clazz");
	}

	public M setCollege(java.lang.String college) {
		set("college", college);
		return (M)this;
	}
	
	public java.lang.String getCollege() {
		return getStr("college");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
