package cn.jbolt.common.model.base;
import cn.jbolt.base.JBoltBaseModel;

/**
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatConfig<M extends BaseWechatConfig<M>> extends JBoltBaseModel<M>{

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 微信 ID
	 */
	public M setMpId(java.lang.Integer mpId) {
		set("mp_id", mpId);
		return (M)this;
	}
	
	/**
	 * 微信 ID
	 */
	public java.lang.Integer getMpId() {
		return getInt("mp_id");
	}

	/**
	 * 配置key
	 */
	public M setConfigKey(java.lang.String configKey) {
		set("config_key", configKey);
		return (M)this;
	}
	
	/**
	 * 配置key
	 */
	public java.lang.String getConfigKey() {
		return getStr("config_key");
	}

	/**
	 * 配置值
	 */
	public M setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
		return (M)this;
	}
	
	/**
	 * 配置值
	 */
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}

	/**
	 * 配置项名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 配置项名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 配置类型
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 配置类型
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
